// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf5rNh3PxttnEFeZvccVqU20mWLpFoeAA',
    appId: '1:1080922785544:web:349da185879f9ea9da8ebd',
    messagingSenderId: '1080922785544',
    projectId: 'chathive-e7829',
    authDomain: 'chathive-e7829.firebaseapp.com',
    storageBucket: 'chathive-e7829.firebasestorage.app',
    measurementId: 'G-PC6D13EYPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs3y0oLIljjED-V9-FKlDaFNCOlqHUap4',
    appId: '1:1080922785544:android:27dac7f260986eccda8ebd',
    messagingSenderId: '1080922785544',
    projectId: 'chathive-e7829',
    storageBucket: 'chathive-e7829.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB52ATybQziQGTv1qNeF3uLKoxb8QcSxvw',
    appId: '1:1080922785544:ios:02afacbe9772d507da8ebd',
    messagingSenderId: '1080922785544',
    projectId: 'chathive-e7829',
    storageBucket: 'chathive-e7829.firebasestorage.app',
    iosBundleId: 'com.example.chatHive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB52ATybQziQGTv1qNeF3uLKoxb8QcSxvw',
    appId: '1:1080922785544:ios:02afacbe9772d507da8ebd',
    messagingSenderId: '1080922785544',
    projectId: 'chathive-e7829',
    storageBucket: 'chathive-e7829.firebasestorage.app',
    iosBundleId: 'com.example.chatHive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf5rNh3PxttnEFeZvccVqU20mWLpFoeAA',
    appId: '1:1080922785544:web:55e335768abfbbf3da8ebd',
    messagingSenderId: '1080922785544',
    projectId: 'chathive-e7829',
    authDomain: 'chathive-e7829.firebaseapp.com',
    storageBucket: 'chathive-e7829.firebasestorage.app',
    measurementId: 'G-SRXTS34SCQ',
  );
}
